version: 2
jobs:
  build:
    branches:
      only:
      - master
      - develop
      - addinCircleCI

    docker:
    - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/java-tron
    steps:
    - checkout
    - run:
        name: multi_os_result
        command: echo "curl http://60.205.215.34/multi_os_result"
#
#    - run:
#        name: Daily Build Report
#        command: curl http://47.95.206.44:50080/Daily_Build_Task_Report
#
#    - run:
#        name: Download Links
#        command: sh DownloadLinks.sh

